  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - server:server


  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: bekhterev
      MONGO_INITDB_ROOT_PASSWORD: pgastest
      MONGO_INITDB_DATABASE: bekhterev
    volumes:
      - "./data:/data/db"
    ports:
      - "27017:27017"

  server:
    image: node
    working_dir: /opt/
    environment:
      LDAP_URL: ldap://srvdc.ad.pu.ru
      DB_USER: bekhterev
      DB_PASSWORD: pgastest
      DB_HOST: mongo
      DB_NAME: bekhterev
    command: bash -c "npm start"
    ports:
      - "8080:8080"
    links:
      - mongo:mongo
    volumes:
      - "./tmp:/tmp/"
      - ".:/opt/"
      - "./rtmp:/rtmp"

